# 必读！！！
# 此版本没有做防泄露处理，如介意请使用另一个名字为configdns的版本
# 注意规则在满足自己需求情况下，尽量做到精简，不要过度复杂，以免影响性能。
# 跑裸核用户请自行去掉下方控制面板模块的注释。
# 机场订阅
port: 8080
socks-port: 1080
redir-port: 7891
mixed-port: 7890
allow-lan: true
unified-delay: true
mode: rule
log-level: warning
ipv6: true
external-controller: '[::]:9095'
clash-for-android:
  append-system-dns: false
profile:
  tracing: true
  store-selected: true
  store-fake-ip: true
experimental:
  sniff-tls-sni: true
dns:
  enable: true
  ipv6: true
  listen: '[::]:1053'
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - +.lan
    - +.local
    - geosite:cn
    - fly.olddrivers.cc
    - 156.246.92.61
    - +.olddrivers.cc
    - +.rocki.top
  fake-ip-filter-mode: blacklist
  respect-rules: true
  use-hosts: true
  default-nameserver:
    - 223.5.5.5
    - 8.8.8.8
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
    - https://dns.google/dns-query
  nameserver:
    - https://223.5.5.5/dns-query
    - 192.168.1.250:6053
  fallback:
    - 8.8.8.8
    - https://dns.google/dns-query
    - https://dns.cloudflare.com/dns-query
  direct-nameserver-follow-policy: false
  nameserver-policy:
    geosite:private,cn:
      - https://223.5.5.5/dns-query
      - 192.168.1.250:6053
    geosite:geolocation-!cn:
      - https://1.1.1.1/dns-query
      - 8.8.8.8
    '*.olddrivers.cc':
      - 223.5.5.5

find-process-mode: off
tcp-concurrent: true
keep-alive-idle: 600
keep-alive-interval: 15
external-ui: ui
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist-cdn-fonts.zip
secret: "378467"
tproxy-port: 7892
tun:
  enable: true
  device: nikki
  stack: mixed
  dns-hijack:
    - tcp://any:53
    - udp://any:53
  auto-route: false
  auto-redirect: false
  auto-detect-interface: false
  disable-icmp-forwarding: true
hosts:
  mc.rocki.top:
    - 192.168.1.11
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
geodata-mode: false
geodata-loader: standard
geox-url:
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
geo-auto-update: true
geo-update-interval: 86400


proxy-providers:
  Airport1:
    url: "https://sub.olddrivers.cc/wxCSfuP5xm4zELXBp6qS/download/collection/1st?target=ClashMeta"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: 直连

# 节点信息
proxies:
  - {name: 直连, type: direct}


 
# 出站策略，根据自己情况调整每个策略里分组排序，增删都可以，比如把美国自动放到第一个，比如删除香港故转，注意别漏掉表情逗号等。
# 如果相应分组没有筛选到对应的国家，请根据自己节点名字调整筛选关键字。
# 没有再使用锚点，是考虑很多新手修改难度，这样新手修改某个分组更容易些。
proxy-groups:
  - {name: 🇭🇰 香港节点, type: select, include-all-providers: true, filter: "(?i)(?=.*(港|HK|Hong))^((?!(台|日(?!用)|韩|新|深|美)).)*$"}
  - {name: 🇯🇵 日本节点, type: select, include-all-providers: true, filter: "(?i)(?=.*(日本|日(?!用)|JP|Japan))^((?!(港|台|韩|新|美)).)*$"}
  - {name: 🇸🇬 狮城节点, type: select, include-all-providers: true, filter: "(?i)(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!(台|日(?!用)|韩|深|美)).)*$"}
  - {name: 🇺🇲 美国节点, type: select, include-all-providers: true, filter: "(?i)(?=.*(美|US|States|America))^((?!(港|台|韩|新|日(?!用))).)*$"}
  - {name: 特殊, type: select, include-all: true}
  - {name: 特殊2, type: select, include-all: true}
  - {name: 🌐 全部节点, type: select, include-all: true}
  - {name: Final,type: select, proxies: [🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,特殊,特殊2]}
  - {name: 节点选择日本, type: select, proxies: [🇯🇵 日本节点, 直连]}
  - {name: 节点选择新加坡, type: select, proxies: [🇸🇬 狮城节点,直连]}
  - {name: 节点选择香港, type: select, proxies: [🇭🇰 香港节点, 直连]}
  - {name: 节点选择美国, type: select, proxies: [🇺🇲 美国节点, 直连]}
  - {name: 🐟 漏网之鱼, type: select, proxies: [🇭🇰 香港节点,🇯🇵 日本节点,🇸🇬 狮城节点,🇺🇲 美国节点,特殊,特殊2]}
# 规则匹配
rules:
  - RULE-SET,private_ip,直连,no-resolve
  - RULE-SET,private_domain,直连
  - RULE-SET,ph,节点选择香港
  - RULE-SET,bank,特殊
  - RULE-SET,oky,特殊
  - RULE-SET,biance,特殊
  - RULE-SET,google,节点选择日本
  - RULE-SET,YouTube,节点选择日本
  - RULE-SET,us,节点选择美国
  - RULE-SET,openAI,节点选择美国
  - RULE-SET,Claude,特殊
  - RULE-SET,adobe,节点选择香港
  - RULE-SET,direct,直连
  - RULE-SET,wechat,直连
  - RULE-SET,EA,直连
  - RULE-SET,Steam,直连
  - RULE-SET,xiaomi,直连
  - RULE-SET,apple_ip,直连
  - RULE-SET,apple_domain,直连
  - RULE-SET,Microsoft,直连
  - RULE-SET,logi,直连
  - RULE-SET,cn_domain,直连
  - RULE-SET,cn_ip,直连
  - RULE-SET,geolocation-!cn,Final
  - MATCH,🐟 漏网之鱼

# 规则集
## type：可选http/file/inline  behavior：可选domain/ipcidr/classical format：可选yaml/text/mrs
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
rule-providers: 
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}
  private_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
  apple_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geoip/apple.mrs"}
  apple_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}
  geolocation-!cn: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  private_ip: {<<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  adobe:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Adobe/Adobe.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  openAI:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  logi:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Logitech/Logitech.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  apple:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  apple-domain:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple_Domain.txt
    proxy: GLOBAL
    size_limit: "0"
    format: text
    behavior: domain
    interval: "86400"
  EA:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/EA/EA.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  Steam:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  AppleStore:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AppStore/AppStore.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  google:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  oky:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OKX/OKX.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  biance:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Binance/Binance.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  Microsoft:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  YouTube:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  wechat:
    type: http
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/WeChat/WeChat.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  xiaomi:
    type: http
    url: https://testingcf.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/XiaoMi/XiaoMi.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"  
  direct:
    type: http
    url: https://raw.githubusercontent.com/cheng2004237/gfwsub/refs/heads/main/direct.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  ph:
    type: http
    url: https://raw.githubusercontent.com/cheng2004237/gfwsub/refs/heads/main/ph.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  us:
    type: http
    url: https://raw.githubusercontent.com/cheng2004237/gfwsub/refs/heads/main/us.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  Claude:
    type: http
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"
  bank:
    type: http
    url: https://raw.githubusercontent.com/cheng2004237/gfwsub/refs/heads/main/bank.yaml
    proxy: GLOBAL
    size_limit: "0"
    format: yaml
    behavior: classical
    interval: "86400"